apiVersion: "tensorflow.org/v1alpha1"
kind: "TfJob"
metadata:
  name: "bigdata-vilnius"
  labels: 
    name: bigdata-vilnius
spec:
  replicaSpecs:
    - replicas: 1
      tfReplicaType: MASTER
      template:
        spec:
          containers:
            - image: krallistic/tf-dist-example:latest
              name: tensorflow
          restartPolicy: OnFailure
    - replicas: 2
      tfReplicaType: WORKER
      template:
        spec:
          containers:
            - image: krallistic/tf-dist-example:latest
              name: tensorflow
          restartPolicy: OnFailure
    - replicas: 1
      tfReplicaType: PS
  tensorboard:
    logDir: gs://krallistic-bigdata-vilnius/logdir/