apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helloworld.meetup.example.com
spec:
  group: meetup.example.com
  version: v1
  scope: Namespaced
  names:
    plural: helloworld
    singular: helloworld
    kind: helloworld
    shortNames:
    - hello
    - hw
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
