kind: Pod
apiVersion: v1
metadata:
  name: gpu-pod-mnist
spec:
  containers:
  - name: gpu-container
    image: krallistic/mnist-single-gpu:latest
    imagePullPolicy: Always
    resources:
      requests: #Optional
        alpha.kubernetes.io/nvidia-gpu: 1
      limits:
        alpha.kubernetes.io/nvidia-gpu: 1
    volumeMounts:
    - name: nvidia-driver-375-66
      mountPath: /usr/local/nvidia
      readOnly: true
    - name: libcuda-so
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so
    - name: libcuda-so-1
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
    - name: libcuda-so-375-66
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.375.66
  restartPolicy: Never
  volumes:
  - name: nvidia-driver-375-66
    hostPath:
      path: /var/lib/nvidia-docker/volumes/nvidia_driver/375.66
  - name: libcuda-so
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so
  - name: libcuda-so-1
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
  - name: libcuda-so-375-66
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so.375.66